import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {PokeyAudio,POKEY_CLOCK} from './pokey-audio.js';
import {BattlezoneDiscrete} from './discrete-audio.js';
import {BzoneAudio} from './audio.js';

test('all 256 AUDCTL routes match 2,097,152 MAME 0.289 POKEY raw clock outputs',()=>{
 const hash=createHash('sha256'),data=Buffer.alloc(8192*2);
 for(let a=0;a<256;a++) {
  const p=new PokeyAudio();p.write(15,3);p.write(8,a);
  for(let c=0;c<4;c++){p.write(c*2,3+c*7);p.write(c*2+1,(((a+c)%8)<<5)|((c+1)*3));}
  p.write(9,0);
  for(let n=0;n<8192;n++){p.step();data.writeUInt16LE(p.raw,n*2);}
  hash.update(data);
 }
 // Generated by test-support/mame-pokey-reference.py from the original C++ methods.
 assert.equal(hash.digest('hex'),'f2063c2c2f4c6fa9e1e0e5ece3bed8896514517146bce908ec58e96289098d05');
});

test('shell/explosion filters and engine CV/555 match original MAME STEP bodies',()=>{
 const rows=JSON.parse(readFileSync(new URL('./test-support/discrete-reference.json',import.meta.url)));
 const d=new BattlezoneDiscrete(48000);let next=0;
 for(let n=0;n<192000;n++) {
  const latch=Math.floor(n/12000)*17;
  const shell=d.shell.step(latch&4,(Math.floor(n/31)&1),(latch>>1)&1);
  const explosion=d.explosion.step(latch&1,(Math.floor(n/79)&1),(latch>>1)&1);
  const r=latch&16?1/(1/1270+1/4700):4700,diff=5*r/(1000+r)-d.cv;
  d.cv+=diff*(diff>.5?d.cvFast:d.cvSlow);d.oscillator();
  if(rows[next]?.[0]===n) {
   const actual=[shell,explosion,d.cv,d.vco,d.cap];
   actual.forEach((v,i)=>assert.ok(Math.abs(v-rows[next][i+1])<1e-9,`sample ${n}, node ${i}`));next++;
  }
 }
 assert.equal(next,rows.length);
});

function audioFixture(sr=48000) {
 globalThis.window={AudioContext:class {
  constructor(){this.sampleRate=sr;this.state='running';}
  createScriptProcessor(){return {connect(){}};}
 }};
 const game={cpu:{cycles:0},paused:false,in3:()=>0x21};
 const audio=new BzoneAudio(game);audio.start();return {audio,game};
}
test('CPU writes are clocked before applying registers and mute covers every sound',()=>{
 const {audio:a,game:g}=audioFixture();
 a.write(15,7);a.write(0,24);a.write(1,0xaf);a.write(9,0);a.control(0xa7);
 g.cpu.cycles=1000;a.write(0,50);
 assert.equal(a.audioCycle,1000);assert.equal(a.pokey.reg[0],50);
 g.cpu.cycles=POKEY_CLOCK;a.sync();assert.equal(a.overruns>0,true);
 a.control(0);const d=a.discrete;
 for(let i=0;i<1000;i++)assert.equal(d.step(5),0);
 assert.equal(a.read(8),0x21);
});

test('60/120 Hz browser frames keep 41 Hz game timing and feed audio without gaps',()=>{
 const source=readFileSync(new URL('./script.js',import.meta.url),'utf8');
 const run=source.slice(source.indexOf(' run(){')+1,source.indexOf('\n bind(){'));
 for(const hz of [60,120])for(const sr of [44100,48000]) {
  const {audio,game}=audioFixture(sr);let scheduled;
  const ctx={FPS:POKEY_CLOCK/6144/6,requestAnimationFrame:fn=>scheduled=fn};
  vm.createContext(ctx);const start=vm.runInContext('({'+run+'}).run',ctx);
  let frames=0;
  const stub={paused:false,frame(){frames++;game.cpu.cycles+=36864;audio.sync();}};
  start.call(stub);scheduled(0);
  let nextAudio=1024/sr,nextFrame=1/hz;
  const buffer=new Float32Array(1024);
  while(Math.min(nextAudio,nextFrame)<=5) {
   if(nextAudio<nextFrame){audio.render(buffer);nextAudio+=1024/sr;}
   else {scheduled(nextFrame*1000);nextFrame+=1/hz;}
  }
  assert.ok(Math.abs(frames-(nextFrame-1/hz)*ctx.FPS)<1,`${hz} Hz, ${sr} Hz`);
  assert.equal(audio.underruns,0);assert.equal(audio.overruns,0);
 }
});
